CREATE INDEX [IDX_CLR_EXT_20160927_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20160927] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20161027_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20161027] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20161128_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20161128] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20161229_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20161229] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20170126_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20170126] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20170227_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20170227] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20170324_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20170324] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20170427_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20170427] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20170626_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20170626] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20170727_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20170727] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20170825_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20170825] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20170928_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20170928] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20171026_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20171026] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20171128_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20171128] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20171228_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20171228] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20180228_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20180228] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20180327_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20180327] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20180426_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20180426] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20180529_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20180529] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20180628_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20180628] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20180829_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20180829] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20181129_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20181129] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20181224_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20181224] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20190128_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20190128] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20190228_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20190228] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20190327_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20190327] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20190429_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20190429] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20190628_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20190628] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20190729_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20190729] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20190829_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20190829] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20180730_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20180730] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20190927_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20190927] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20191028_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20191028] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20191128_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20191128] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20191224_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20191224] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20200127_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20200127] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20200227_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20200227] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20200330_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20200330] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20200427_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20200427] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20200525_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20200525] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20200629_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20200629] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20200729_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20200729] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20200825_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20200825] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20201130_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20201130] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20201229_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20201229] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20210128_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20210128] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20210225_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20210225] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20210430_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20210430] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20210609_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20210609] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20210628_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20210628] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20210729_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20210729] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20210830_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20210830] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20210927_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20210927] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20211028_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20211028] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20211129_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20211129] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20211230_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20211230] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20220128_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20220128] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20220228_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20220228] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20220330_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20220330] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20220430_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20220430] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20220530_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20220530] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20220627_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20220627] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20220728_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20220728] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20220829_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20220829] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20220927_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20220927] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_202201028_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_202201028] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_202201129_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_202201129] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20230103_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20230103] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20230227_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20230227] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_BC_STAT_POPULATION_ESTIMATES_20230327_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[BC_STAT_POPULATION_ESTIMATES_20230327] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20230426_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20230426] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20230525_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20230525] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20230626_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20230626] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20230726_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20230726] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20230828_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20230828] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20230927_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20230927] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20231030_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20231030] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20231127_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20231127] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_CLR_EXT_20231227_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[CLR_EXT_20231227] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_BC_STAT_POPULATION_ESTIMATES_20240129_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[BC_STAT_POPULATION_ESTIMATES_20240129] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_BC_STAT_POPULATION_ESTIMATES_20240226_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[BC_STAT_POPULATION_ESTIMATES_20240226] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_BC_STAT_POPULATION_ESTIMATES_20240326_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[BC_STAT_POPULATION_ESTIMATES_20240326] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_BC_STAT_POPULATION_ESTIMATES_20240429_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[BC_STAT_POPULATION_ESTIMATES_20240429] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_BC_STAT_POPULATION_ESTIMATES_20240527_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[BC_STAT_POPULATION_ESTIMATES_20240527] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_BC_STAT_POPULATION_ESTIMATES_20240628_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[BC_STAT_POPULATION_ESTIMATES_20240628] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_BC_STAT_POPULATION_ESTIMATES_20240726_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[BC_STAT_POPULATION_ESTIMATES_20240726] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_BC_STAT_POPULATION_ESTIMATES_20240827_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[BC_STAT_POPULATION_ESTIMATES_20240827] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

CREATE INDEX [IDX_bc_stat_population_estimates_20240926_STUDY_ID_EFF_DATE_POSTAL_CODE_STREET_LINE]
ON [dev].[bc_stat_population_estimates_20240926] ([STUDY_ID], [EFF_DATE], [POSTAL_CODE], [STREET_LINE]);

