SELECT
    C.STUDY_ID,
    T1.[POSTAL_CODE],
    T1.[STREET_LINE],
    T1.[EFF_DATE],
    T1.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20160927 T1
   ON C.STUDY_ID = T1.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T2.[POSTAL_CODE],
    T2.[STREET_LINE],
    T2.[EFF_DATE],
    T2.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20161027 T2
   ON C.STUDY_ID = T2.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T3.[POSTAL_CODE],
    T3.[STREET_LINE],
    T3.[EFF_DATE],
    T3.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20161128 T3
   ON C.STUDY_ID = T3.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T4.[POSTAL_CODE],
    T4.[STREET_LINE],
    T4.[EFF_DATE],
    T4.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20161229 T4
   ON C.STUDY_ID = T4.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T5.[POSTAL_CODE],
    T5.[STREET_LINE],
    T5.[EFF_DATE],
    T5.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20170126 T5
   ON C.STUDY_ID = T5.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T6.[POSTAL_CODE],
    T6.[STREET_LINE],
    T6.[EFF_DATE],
    T6.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20170227 T6
   ON C.STUDY_ID = T6.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T7.[POSTAL_CODE],
    T7.[STREET_LINE],
    T7.[EFF_DATE],
    T7.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20170324 T7
   ON C.STUDY_ID = T7.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T8.[POSTAL_CODE],
    T8.[STREET_LINE],
    T8.[EFF_DATE],
    T8.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20170427 T8
   ON C.STUDY_ID = T8.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T9.[POSTAL_CODE],
    T9.[STREET_LINE],
    T9.[EFF_DATE],
    T9.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20170626 T9
   ON C.STUDY_ID = T9.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T10.[POSTAL_CODE],
    T10.[STREET_LINE],
    T10.[EFF_DATE],
    T10.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20170727 T10
   ON C.STUDY_ID = T10.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T11.[POSTAL_CODE],
    T11.[STREET_LINE],
    T11.[EFF_DATE],
    T11.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20170825 T11
   ON C.STUDY_ID = T11.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T12.[POSTAL_CODE],
    T12.[STREET_LINE],
    T12.[EFF_DATE],
    T12.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20170928 T12
   ON C.STUDY_ID = T12.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T13.[POSTAL_CODE],
    T13.[STREET_LINE],
    T13.[EFF_DATE],
    T13.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20171026 T13
   ON C.STUDY_ID = T13.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T14.[POSTAL_CODE],
    T14.[STREET_LINE],
    T14.[EFF_DATE],
    T14.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20171128 T14
   ON C.STUDY_ID = T14.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T15.[POSTAL_CODE],
    T15.[STREET_LINE],
    T15.[EFF_DATE],
    T15.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20171228 T15
   ON C.STUDY_ID = T15.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T16.[POSTAL_CODE],
    T16.[STREET_LINE],
    T16.[EFF_DATE],
    T16.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20180228 T16
   ON C.STUDY_ID = T16.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T17.[POSTAL_CODE],
    T17.[STREET_LINE],
    T17.[EFF_DATE],
    T17.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20180327 T17
   ON C.STUDY_ID = T17.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T18.[POSTAL_CODE],
    T18.[STREET_LINE],
    T18.[EFF_DATE],
    T18.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20180426 T18
   ON C.STUDY_ID = T18.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T19.[POSTAL_CODE],
    T19.[STREET_LINE],
    T19.[EFF_DATE],
    T19.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20180529 T19
   ON C.STUDY_ID = T19.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T20.[POSTAL_CODE],
    T20.[STREET_LINE],
    T20.[EFF_DATE],
    T20.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20180628 T20
   ON C.STUDY_ID = T20.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T21.[POSTAL_CODE],
    T21.[STREET_LINE],
    T21.[EFF_DATE],
    T21.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20180829 T21
   ON C.STUDY_ID = T21.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T22.[POSTAL_CODE],
    T22.[STREET_LINE],
    T22.[EFF_DATE],
    T22.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20181129 T22
   ON C.STUDY_ID = T22.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T23.[POSTAL_CODE],
    T23.[STREET_LINE],
    T23.[EFF_DATE],
    T23.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20181224 T23
   ON C.STUDY_ID = T23.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T24.[POSTAL_CODE],
    T24.[STREET_LINE],
    T24.[EFF_DATE],
    T24.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20190128 T24
   ON C.STUDY_ID = T24.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T25.[POSTAL_CODE],
    T25.[STREET_LINE],
    T25.[EFF_DATE],
    T25.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20190228 T25
   ON C.STUDY_ID = T25.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T26.[POSTAL_CODE],
    T26.[STREET_LINE],
    T26.[EFF_DATE],
    T26.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20190327 T26
   ON C.STUDY_ID = T26.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T27.[POSTAL_CODE],
    T27.[STREET_LINE],
    T27.[EFF_DATE],
    T27.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20190429 T27
   ON C.STUDY_ID = T27.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T28.[POSTAL_CODE],
    T28.[STREET_LINE],
    T28.[EFF_DATE],
    T28.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20190628 T28
   ON C.STUDY_ID = T28.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T29.[POSTAL_CODE],
    T29.[STREET_LINE],
    T29.[EFF_DATE],
    T29.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20190729 T29
   ON C.STUDY_ID = T29.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T30.[POSTAL_CODE],
    T30.[STREET_LINE],
    T30.[EFF_DATE],
    T30.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20190829 T30
   ON C.STUDY_ID = T30.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T31.[POSTAL_CODE],
    T31.[STREET_LINE],
    T31.[EFF_DATE],
    T31.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20180730 T31
   ON C.STUDY_ID = T31.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T32.[POSTAL_CODE],
    T32.[STREET_LINE],
    T32.[EFF_DATE],
    T32.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20190927 T32
   ON C.STUDY_ID = T32.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T33.[POSTAL_CODE],
    T33.[STREET_LINE],
    T33.[EFF_DATE],
    T33.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20191028 T33
   ON C.STUDY_ID = T33.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T34.[POSTAL_CODE],
    T34.[STREET_LINE],
    T34.[EFF_DATE],
    T34.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20191128 T34
   ON C.STUDY_ID = T34.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T35.[POSTAL_CODE],
    T35.[STREET_LINE],
    T35.[EFF_DATE],
    T35.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20191224 T35
   ON C.STUDY_ID = T35.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T36.[POSTAL_CODE],
    T36.[STREET_LINE],
    T36.[EFF_DATE],
    T36.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20200127 T36
   ON C.STUDY_ID = T36.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T37.[POSTAL_CODE],
    T37.[STREET_LINE],
    T37.[EFF_DATE],
    T37.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20200227 T37
   ON C.STUDY_ID = T37.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T38.[POSTAL_CODE],
    T38.[STREET_LINE],
    T38.[EFF_DATE],
    T38.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20200330 T38
   ON C.STUDY_ID = T38.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T39.[POSTAL_CODE],
    T39.[STREET_LINE],
    T39.[EFF_DATE],
    T39.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20200427 T39
   ON C.STUDY_ID = T39.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T40.[POSTAL_CODE],
    T40.[STREET_LINE],
    T40.[EFF_DATE],
    T40.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20200525 T40
   ON C.STUDY_ID = T40.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T41.[POSTAL_CODE],
    T41.[STREET_LINE],
    T41.[EFF_DATE],
    T41.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20200629 T41
   ON C.STUDY_ID = T41.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T42.[POSTAL_CODE],
    T42.[STREET_LINE],
    T42.[EFF_DATE],
    T42.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20200729 T42
   ON C.STUDY_ID = T42.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T43.[POSTAL_CODE],
    T43.[STREET_LINE],
    T43.[EFF_DATE],
    T43.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20200825 T43
   ON C.STUDY_ID = T43.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T44.[POSTAL_CODE],
    T44.[STREET_LINE],
    T44.[EFF_DATE],
    T44.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20201130 T44
   ON C.STUDY_ID = T44.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T45.[POSTAL_CODE],
    T45.[STREET_LINE],
    T45.[EFF_DATE],
    T45.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20201229 T45
   ON C.STUDY_ID = T45.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T46.[POSTAL_CODE],
    T46.[STREET_LINE],
    T46.[EFF_DATE],
    T46.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20210128 T46
   ON C.STUDY_ID = T46.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T47.[POSTAL_CODE],
    T47.[STREET_LINE],
    T47.[EFF_DATE],
    T47.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20210225 T47
   ON C.STUDY_ID = T47.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T48.[POSTAL_CODE],
    T48.[STREET_LINE],
    T48.[EFF_DATE],
    T48.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20210430 T48
   ON C.STUDY_ID = T48.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T49.[POSTAL_CODE],
    T49.[STREET_LINE],
    T49.[EFF_DATE],
    T49.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20210609 T49
   ON C.STUDY_ID = T49.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T50.[POSTAL_CODE],
    T50.[STREET_LINE],
    T50.[EFF_DATE],
    T50.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20210628 T50
   ON C.STUDY_ID = T50.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T51.[POSTAL_CODE],
    T51.[STREET_LINE],
    T51.[EFF_DATE],
    T51.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20210729 T51
   ON C.STUDY_ID = T51.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T52.[POSTAL_CODE],
    T52.[STREET_LINE],
    T52.[EFF_DATE],
    T52.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20210830 T52
   ON C.STUDY_ID = T52.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T53.[POSTAL_CODE],
    T53.[STREET_LINE],
    T53.[EFF_DATE],
    T53.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20210927 T53
   ON C.STUDY_ID = T53.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T54.[POSTAL_CODE],
    T54.[STREET_LINE],
    T54.[EFF_DATE],
    T54.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20211028 T54
   ON C.STUDY_ID = T54.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T55.[POSTAL_CODE],
    T55.[STREET_LINE],
    T55.[EFF_DATE],
    T55.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20211129 T55
   ON C.STUDY_ID = T55.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T56.[POSTAL_CODE],
    T56.[STREET_LINE],
    T56.[EFF_DATE],
    T56.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20211230 T56
   ON C.STUDY_ID = T56.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T57.[POSTAL_CODE],
    T57.[STREET_LINE],
    T57.[EFF_DATE],
    T57.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20220128 T57
   ON C.STUDY_ID = T57.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T58.[POSTAL_CODE],
    T58.[STREET_LINE],
    T58.[EFF_DATE],
    T58.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20220228 T58
   ON C.STUDY_ID = T58.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T59.[POSTAL_CODE],
    T59.[STREET_LINE],
    T59.[EFF_DATE],
    T59.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20220330 T59
   ON C.STUDY_ID = T59.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T60.[POSTAL_CODE],
    T60.[STREET_LINE],
    T60.[EFF_DATE],
    T60.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20220430 T60
   ON C.STUDY_ID = T60.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T61.[POSTAL_CODE],
    T61.[STREET_LINE],
    T61.[EFF_DATE],
    T61.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20220530 T61
   ON C.STUDY_ID = T61.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T62.[POSTAL_CODE],
    T62.[STREET_LINE],
    T62.[EFF_DATE],
    T62.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20220627 T62
   ON C.STUDY_ID = T62.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T63.[POSTAL_CODE],
    T63.[STREET_LINE],
    T63.[EFF_DATE],
    T63.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20220728 T63
   ON C.STUDY_ID = T63.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T64.[POSTAL_CODE],
    T64.[STREET_LINE],
    T64.[EFF_DATE],
    T64.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20220829 T64
   ON C.STUDY_ID = T64.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T65.[POSTAL_CODE],
    T65.[STREET_LINE],
    T65.[EFF_DATE],
    T65.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20220927 T65
   ON C.STUDY_ID = T65.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T66.[POSTAL_CODE],
    T66.[STREET_LINE],
    T66.[EFF_DATE],
    T66.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_202201028 T66
   ON C.STUDY_ID = T66.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T67.[POSTAL_CODE],
    T67.[STREET_LINE],
    T67.[EFF_DATE],
    T67.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_202201129 T67
   ON C.STUDY_ID = T67.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T68.[POSTAL_CODE],
    T68.[STREET_LINE],
    T68.[EFF_DATE],
    T68.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20230103 T68
   ON C.STUDY_ID = T68.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T69.[POSTAL_CODE],
    T69.[STREET_LINE],
    T69.[EFF_DATE],
    T69.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20230227 T69
   ON C.STUDY_ID = T69.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T70.[POSTAL_CODE],
    T70.[STREET_LINE],
    T70.[EFF_DATE],
    T70.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.BC_STAT_POPULATION_ESTIMATES_20230327 T70
   ON C.STUDY_ID = T70.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T71.[POSTAL_CODE],
    T71.[STREET_LINE],
    T71.[EFF_DATE],
    T71.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20230426 T71
   ON C.STUDY_ID = T71.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T72.[POSTAL_CODE],
    T72.[STREET_LINE],
    T72.[EFF_DATE],
    T72.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20230525 T72
   ON C.STUDY_ID = T72.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T73.[POSTAL_CODE],
    T73.[STREET_LINE],
    T73.[EFF_DATE],
    T73.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20230626 T73
   ON C.STUDY_ID = T73.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T74.[POSTAL_CODE],
    T74.[STREET_LINE],
    T74.[EFF_DATE],
    T74.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20230726 T74
   ON C.STUDY_ID = T74.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T75.[POSTAL_CODE],
    T75.[STREET_LINE],
    T75.[EFF_DATE],
    T75.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20230828 T75
   ON C.STUDY_ID = T75.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T76.[POSTAL_CODE],
    T76.[STREET_LINE],
    T76.[EFF_DATE],
    T76.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20230927 T76
   ON C.STUDY_ID = T76.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T77.[POSTAL_CODE],
    T77.[STREET_LINE],
    T77.[EFF_DATE],
    T77.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20231030 T77
   ON C.STUDY_ID = T77.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T78.[POSTAL_CODE],
    T78.[STREET_LINE],
    T78.[EFF_DATE],
    T78.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20231127 T78
   ON C.STUDY_ID = T78.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T79.[POSTAL_CODE],
    T79.[STREET_LINE],
    T79.[EFF_DATE],
    T79.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.CLR_EXT_20231227 T79
   ON C.STUDY_ID = T79.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T80.[POSTAL_CODE],
    T80.[STREET_LINE],
    T80.[EFF_DATE],
    T80.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.BC_STAT_POPULATION_ESTIMATES_20240129 T80
   ON C.STUDY_ID = T80.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T81.[POSTAL_CODE],
    T81.[STREET_LINE],
    T81.[EFF_DATE],
    T81.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.BC_STAT_POPULATION_ESTIMATES_20240226 T81
   ON C.STUDY_ID = T81.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T82.[POSTAL_CODE],
    T82.[STREET_LINE],
    T82.[EFF_DATE],
    T82.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.BC_STAT_POPULATION_ESTIMATES_20240326 T82
   ON C.STUDY_ID = T82.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T83.[POSTAL_CODE],
    T83.[STREET_LINE],
    T83.[EFF_DATE],
    T83.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.BC_STAT_POPULATION_ESTIMATES_20240429 T83
   ON C.STUDY_ID = T83.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T84.[POSTAL_CODE],
    T84.[STREET_LINE],
    T84.[EFF_DATE],
    T84.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.BC_STAT_POPULATION_ESTIMATES_20240527 T84
   ON C.STUDY_ID = T84.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T85.[POSTAL_CODE],
    T85.[STREET_LINE],
    T85.[EFF_DATE],
    T85.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.BC_STAT_POPULATION_ESTIMATES_20240628 T85
   ON C.STUDY_ID = T85.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T86.[POSTAL_CODE],
    T86.[STREET_LINE],
    T86.[EFF_DATE],
    T86.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.BC_STAT_POPULATION_ESTIMATES_20240726 T86
   ON C.STUDY_ID = T86.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T87.[POSTAL_CODE],
    T87.[STREET_LINE],
    T87.[EFF_DATE],
    T87.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.BC_STAT_POPULATION_ESTIMATES_20240827 T87
   ON C.STUDY_ID = T87.STUDY_ID

UNION ALL

SELECT
    C.STUDY_ID,
    T88.[POSTAL_CODE],
    T88.[STREET_LINE],
    T88.[EFF_DATE],
    T88.[END_DATE]
FROM #CurrentBatch C
INNER JOIN dev.bc_stat_population_estimates_20240926 T88
   ON C.STUDY_ID = T88.STUDY_ID
