CREATE VIEW DEV.VIEW_COMBINED_HEALTH_CLIENT_ADDRESS
AS
SELECT 
    [POSTAL_CODE], 
    [STREET_LINE], 
    [CITY],
    MAX([LATITUDE]) AS [LATITUDE],
    MAX([LONGITUDE]) AS [LONGITUDE],
    MAX([CHSA]) AS [CHSA],
    MAX([LHA]) AS [LHA]
FROM DEV.VIEW_COMBINED_HEALTH_CLIENT
GROUP BY 
    [POSTAL_CODE], 
    [STREET_LINE], 
    [CITY];
